spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sk_blog?createDatabaseIfNotExist=true
    username: root
    password: Gold2014
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: false
  sql:
    init:
      mode: never
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.xml
  web:
    resources:
      add-mappings: false
#      static-locations: classpath:/static/
  mvc:
    throw-exception-if-no-handler-found: true











