databaseChangeLog:
  - changeSet:
      id: "1"
      author: SchlechtGut
      changes:
        - insert:
            tableName: global_settings
            columns:
              - column:
                  name: code
                  value: "MULTIUSER_MODE"
              - column:
                  name: name
                  value: "Многопользовательский режим"
              - column:
                  name: value
                  value: "NO"
        - insert:
            tableName: global_settings
            columns:
              - column:
                  name: code
                  value: "POST_PREMODERATION"
              - column:
                  name: name
                  value: "Премодерация постов"
              - column:
                  name: value
                  value: "YES"
        - insert:
            tableName: global_settings
            columns:
              - column:
                  name: code
                  value: "STATISTICS_IS_PUBLIC"
              - column:
                  name: name
                  value: "Показывать всем статистику блога"
              - column:
                  name: value
                  value: "YES"